#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Loja")]
	public partial class LojaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFuncionario(Funcionario instance);
    partial void UpdateFuncionario(Funcionario instance);
    partial void DeleteFuncionario(Funcionario instance);
    #endregion
		
		public LojaDataContext() : 
				base(global::ClassLibrary.Properties.Settings.Default.LojaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LojaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LojaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LojaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LojaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Funcionario> Funcionarios
		{
			get
			{
				return this.GetTable<Funcionario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Funcionario")]
	public partial class Funcionario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _nome;
		
		private string _telefone;
		
		private string _identidade;
		
		private string _carteiraTrabalho;
		
		private System.Nullable<double> _salario;
		
		private System.Nullable<bool> _motorista;
		
		private System.Nullable<bool> _tecnico;
		
		private string _observacao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OntelefoneChanging(string value);
    partial void OntelefoneChanged();
    partial void OnidentidadeChanging(string value);
    partial void OnidentidadeChanged();
    partial void OncarteiraTrabalhoChanging(string value);
    partial void OncarteiraTrabalhoChanged();
    partial void OnsalarioChanging(System.Nullable<double> value);
    partial void OnsalarioChanged();
    partial void OnmotoristaChanging(System.Nullable<bool> value);
    partial void OnmotoristaChanged();
    partial void OntecnicoChanging(System.Nullable<bool> value);
    partial void OntecnicoChanged();
    partial void OnobservacaoChanging(string value);
    partial void OnobservacaoChanged();
    #endregion
		
		public Funcionario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(MAX)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone", DbType="VarChar(MAX)")]
		public string telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				if ((this._telefone != value))
				{
					this.OntelefoneChanging(value);
					this.SendPropertyChanging();
					this._telefone = value;
					this.SendPropertyChanged("telefone");
					this.OntelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identidade", DbType="VarChar(MAX)")]
		public string identidade
		{
			get
			{
				return this._identidade;
			}
			set
			{
				if ((this._identidade != value))
				{
					this.OnidentidadeChanging(value);
					this.SendPropertyChanging();
					this._identidade = value;
					this.SendPropertyChanged("identidade");
					this.OnidentidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carteiraTrabalho", DbType="VarChar(MAX)")]
		public string carteiraTrabalho
		{
			get
			{
				return this._carteiraTrabalho;
			}
			set
			{
				if ((this._carteiraTrabalho != value))
				{
					this.OncarteiraTrabalhoChanging(value);
					this.SendPropertyChanging();
					this._carteiraTrabalho = value;
					this.SendPropertyChanged("carteiraTrabalho");
					this.OncarteiraTrabalhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salario", DbType="Float")]
		public System.Nullable<double> salario
		{
			get
			{
				return this._salario;
			}
			set
			{
				if ((this._salario != value))
				{
					this.OnsalarioChanging(value);
					this.SendPropertyChanging();
					this._salario = value;
					this.SendPropertyChanged("salario");
					this.OnsalarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motorista", DbType="Bit")]
		public System.Nullable<bool> motorista
		{
			get
			{
				return this._motorista;
			}
			set
			{
				if ((this._motorista != value))
				{
					this.OnmotoristaChanging(value);
					this.SendPropertyChanging();
					this._motorista = value;
					this.SendPropertyChanged("motorista");
					this.OnmotoristaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tecnico", DbType="Bit")]
		public System.Nullable<bool> tecnico
		{
			get
			{
				return this._tecnico;
			}
			set
			{
				if ((this._tecnico != value))
				{
					this.OntecnicoChanging(value);
					this.SendPropertyChanging();
					this._tecnico = value;
					this.SendPropertyChanged("tecnico");
					this.OntecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacao", DbType="VarChar(MAX)")]
		public string observacao
		{
			get
			{
				return this._observacao;
			}
			set
			{
				if ((this._observacao != value))
				{
					this.OnobservacaoChanging(value);
					this.SendPropertyChanging();
					this._observacao = value;
					this.SendPropertyChanged("observacao");
					this.OnobservacaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
